[package]
name = "gb_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gameboy = { path = "../gameboy" }
eframe = "0.20.1"
chrono = "0.4.23"
native-dialog = "0.6.3"